version: '2'
services:
  web:
    restart: always
    build: .
    working_dir: /code/arapheno
    command: /usr/local/bin/gunicorn arapheno.wsgi:application -w 2 -b :8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATACITE_USERNAME=${DATACITE_USERNAME}
      - DATACITE_PASSWORD=${DATACITE_PASSWORD}
