version: '2'
services:
  db:
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: unless-stopped
    image: "docker.artifactory.imp.ac.at/the1001genomes/arapheno:latest"
    volumes:
      - /usr/share/nginx/html/static:/usr/share/nginx/html/static
    ports:
      - "8000:8000"
    environment:
      - DATACITE_USERNAME=${DATACITE_USERNAME}
      - DATACITE_PASSWORD=${DATACITE_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - DJANGO_SETTINGS_MODULE=arapheno.settings.prod
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
volumes:
  postgres_data:
