version: "3.7"
services:
  db:
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: unless-stopped
    build: .
    volumes:
      - type: volume
        source: static_files
        target: /srv/static
      - type: bind
        source: ./arapheno/db.sqlite3
        target: /srv/web/arapheno/db.sqlite3
    environment:
      - DATACITE_USERNAME=${DATACITE_USERNAME}
      - DATACITE_PASSWORD=${DATACITE_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - DJANGO_SETTINGS_MODULE=arapheno.settings.prod
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: static_files
        target: /usr/share/nginx/html/static
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: ./arapheno.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
volumes:
  postgres_data:
  static_files:
