version: "3.7"
services:
  db:
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: unless-stopped
    build: .
    volumes:
      - type: bind
        source: /usr/share/nginx/html/static
        target: /usr/share/nginx/html/static
      - type: bind
        source: ./arapheno/db.sqlite3
        target: /srv/web/arapheno/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DATACITE_USERNAME=${DATACITE_USERNAME}
      - DATACITE_PASSWORD=${DATACITE_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - DJANGO_SETTINGS_MODULE=arapheno.settings.prod
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
volumes:
  postgres_data:
