# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0002_auto_20160805_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='firstname',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='lastname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Submitted'), (1, 'Curation'), (2, 'Published')], db_index=True, default=0),
        ),
    ]
