# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0003_auto_20160806_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='study',
        ),
        migrations.AddField(
            model_name='study',
            name='submission',
            field=models.OneToOneField(blank=True, null=True,default=None, on_delete=django.db.models.deletion.CASCADE, to='phenotypedb.Submission'),
            preserve_default=False,
        ),
    ]
