# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0004_auto_20160808_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='phenotypedb.Submission'),
        ),
    ]
