# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0005_auto_20160808_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='study',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='phenotypedb.Study'),
            preserve_default=False,
        ),
    ]
