# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0006_auto_20160808_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotypecuration',
            name='phenotype',
        ),
        migrations.RemoveField(
            model_name='studycuration',
            name='study',
        ),
        migrations.AddField(
            model_name='submission',
            name='curation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='publisher',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhenotypeCuration',
        ),
        migrations.DeleteModel(
            name='StudyCuration',
        ),
    ]
