# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0007_auto_20160811_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='publisher',
            field=models.CharField(default='testt', max_length=200),
        ),
    ]
