# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0008_auto_20160811_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotype',
            name='doi',
        ),
        migrations.AlterField(
            model_name='submission',
            name='publisher',
            field=models.CharField(max_length=200),
        ),
    ]
