# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0009_auto_20160811_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenotype',
            name='update_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
