# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0011_auto_20160812_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenotype',
            name='curation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phenotypedb.Curation'),
        ),
    ]
