# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0012_phenotype_curation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenotypeCuration',
            fields=[
                ('correct', models.BooleanField()),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phenotype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='phenotypedb.Phenotype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyCuration',
            fields=[
                ('correct', models.BooleanField()),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='phenotypedb.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='curation',
        ),
        migrations.RemoveField(
            model_name='study',
            name='curation',
        ),
        migrations.DeleteModel(
            name='Curation',
        ),
    ]
