# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0013_auto_20160813_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotypecuration',
            name='phenotype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='curation', serialize=False, to='phenotypedb.Phenotype'),
        ),
        migrations.AlterField(
            model_name='studycuration',
            name='study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='curation', serialize=False, to='phenotypedb.Study'),
        ),
    ]
