# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-05 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0016_ontologysource_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotype',
            name='source',
        ),
    ]
