# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0017_remove_phenotype_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotype',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Quantitive'), (1, 'Categorical'), (2, 'Binary')], db_index=True, null=True),
        ),
    ]
