# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0018_auto_20190505_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(null=True, to='phenotypedb.Author'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
