# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0021_auto_20190729_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNASeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('scoring', models.TextField(blank=True, null=True)),
                ('shapiro_test_statistic', models.FloatField(blank=True, null=True)),
                ('shapiro_p_value', models.FloatField(blank=True, null=True)),
                ('number_replicates', models.IntegerField(default=0)),
                ('integration_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypedb.Species')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypedb.Study')),
            ],
        ),
        migrations.CreateModel(
            name='RNASeqValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('obs_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypedb.ObservationUnit')),
                ('rnaseq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypedb.RNASeq')),
            ],
        ),
    ]
